spring:
  datasource:
    url: jdbc:sqlserver://192.168.2.185:1433;databaseName=USERINFO
    username: nb1001
    password: nb1001
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    properties:
      hibernate:
      format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true


